---
- name: Ansiblize Managed Hosts   ### Play to connect to all managed nodes in inventory and setup systems to be managed by Ansible
  hosts: all

### Creation of Variables for the playbook's plays and tasks.
### This will define variables allowing the playbook to be reused easier
  vars_files:
    # Contains variables for the Ansible User Creation
    - variables.yml

### Creation of Variables for plays and tasks the are locally seclectable

  vars:
    ssh_key_file: Files/id_rsa.pub 

  tasks:

    ### Create the Ansible User
    - name: Create Ansible User
      user:
        name: "{{ ansible_user_name }}"
        state: present
        shell: /bin/bash
        comment: Ansible User for System


    ### Create the Ansible User
    - name: Create Ansible User Password (if required)
      shell: echo {{ ansible_user_password }} | passwd {{ ansible_user_name }} --stdin

    ### Copy Ansible User Public SSH Keys (if defined)
    ### This will take the public key and set as the authorized_key from the current user
    ### Only works if the current user/remote user is the same as user being created
    - name: Copy Ansible User SSH Keys
      authorized_key:
        user: "{{ ansible_user_name }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

    ### Copy Ansible User Public SSH Keys from file (if defined)
    ### This will take the public key specified and set as and authorized_key for the user specified
    - name: Copy Ansible User SSH Keys
      authorized_key:
        user: "{{ ansible_user_name }}"
        state: present
        key: "{{ ssh_key_file }}"

    ### Modify Sudoers to Allow Passwordless SUDO
    - name: Create Ansible User SUDOERS Entry
      copy:
        content: "{{ ansible_user_name }} ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/{{ ansible_user_name }}

    ### Modify SSH_CONFIG to prevent Root Login
    - name: Prevent Root Login via SSH (if required)
      debug:
        msg: This sill use the Line in File module

    ### Modify SSH_CONFIG to permit SSH Key ONLY Access (no passwords)
    - name: Prevent Root Login via SSH (if required)
      debug:
        msg: This sill use the Line in File module

  handlers:

    ### Restart SSHD if Config File was Changed
    - name: Restart SSHD
      debug:
        msg: This sill use the SERVICE or SYSTEMD
